const { app, BrowserWindow, ipcMain, dialog } = require('electron');
const path = require('path');
const fs = require('fs');
const os = require('os');

// Path to app icon (use .ico for Windows)
const ICON_PATH = path.join(__dirname, 'icon.ico');

let mainWindow;

// Default VST paths by platform
const getVstPaths = () => {
  const platform = os.platform();
  const paths = [];

  if (platform === 'win32') {
    // Windows VST paths
    paths.push(
      'C:\\Program Files\\VstPlugins',
      'C:\\Program Files\\Steinberg\\VstPlugins',
      'C:\\Program Files\\Common Files\\VST2',
      'C:\\Program Files\\Common Files\\VST3',
      'C:\\Program Files (x86)\\VstPlugins',
      'C:\\Program Files (x86)\\Steinberg\\VstPlugins',
      path.join(os.homedir(), 'AppData', 'Local', 'Programs', 'Common', 'VST3')
    );
  } else if (platform === 'darwin') {
    // macOS VST paths
    paths.push(
      '/Library/Audio/VST',
      '/Library/Audio/VST3',
      path.join(os.homedir(), 'Library', 'Audio', 'VST'),
      path.join(os.homedir(), 'Library', 'Audio', 'VST3')
    );
  } else if (platform === 'linux') {
    // Linux VST paths
    paths.push(
      '/usr/lib/vst',
      '/usr/lib/lxvst',
      '/usr/local/lib/vst',
      path.join(os.homedir(), '.vst'),
      path.join(os.homedir(), '.lxvst')
    );
  }

  return paths;
};

// Scan for VST plugins
const scanVstPlugins = () => {
  const vstPaths = getVstPaths();
  const found = [];

  for (const vstPath of vstPaths) {
    if (fs.existsSync(vstPath)) {
      try {
        const files = fs.readdirSync(vstPath);
        const platform = os.platform();
        
        for (const file of files) {
          const isVst = 
            (platform === 'win32' && (file.endsWith('.dll') || file.endsWith('.vst3'))) ||
            (platform === 'darwin' && (file.endsWith('.vst') || file.endsWith('.vst3'))) ||
            (platform === 'linux' && (file.endsWith('.so') || file.endsWith('.vst3')));
          
          if (isVst) {
            found.push({
              name: file,
              path: path.join(vstPath, file),
              folder: vstPath
            });
          }
        }
      } catch (err) {
        console.error(`Error scanning ${vstPath}:`, err);
      }
    }
  }

  return found;
};

// Custom folder selection
const selectVstFolder = async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    properties: ['openDirectory'],
    title: 'Select VST Plugins Folder'
  });

  if (!result.canceled && result.filePaths.length > 0) {
    const folder = result.filePaths[0];
    const files = fs.readdirSync(folder);
    const platform = os.platform();
    
    const vsts = files.filter(file => 
      (platform === 'win32' && (file.endsWith('.dll') || file.endsWith('.vst3'))) ||
      (platform === 'darwin' && (file.endsWith('.vst') || file.endsWith('.vst3'))) ||
      (platform === 'linux' && (file.endsWith('.so') || file.endsWith('.vst3')))
    ).map(file => ({
      name: file,
      path: path.join(folder, file),
      folder: folder
    }));

    return vsts;
  }

  return [];
};

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1200,
    minHeight: 700,
    title: 'MJM AI Timbre - Arpeggiator',
    icon: ICON_PATH,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: false,
    },
    backgroundColor: '#1a1a1a',
    show: false,
  });

  // Load the renderer
  // If running in development with '--dev', we want to load the local vite dev server
  const isDev = process.argv.includes('--dev');
  if (isDev) {
    mainWindow.loadURL('http://localhost:5173');
    mainWindow.webContents.openDevTools();
  } else {
    // In production, the built React app is in the 'dist' folder generated by vite
    mainWindow.loadFile(path.join(__dirname, 'dist', 'index.html'));
  }

  // Show window when ready
  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// IPC Handlers
ipcMain.handle('scan-vst', async () => {
  console.log('Scanning for VST plugins...');
  const plugins = scanVstPlugins();
  console.log(`Found ${plugins.length} VST plugins`);
  return plugins;
});

ipcMain.handle('open-vst', async (event, pluginPath) => {
  console.log(`Attempting to open VST plugin: ${pluginPath}`);
  try {
    // VST plugins cannot be loaded directly as web pages
    // They require a proper VST host application to load and display their native GUI
    // For now, we'll show a placeholder window with plugin information
    // and provide instructions for proper VST hosting
    
    const pluginName = path.basename(pluginPath);
    const pluginDir = path.dirname(pluginPath);
    
    const vstWindow = new BrowserWindow({
      width: 800,
      height: 600,
      minWidth: 600,
      minHeight: 400,
      title: `VST Plugin: ${pluginName}`,
      icon: ICON_PATH,
      webPreferences: {
        preload: path.join(__dirname, 'preload.js'),
        nodeIntegration: false,
        contextIsolation: true,
        sandbox: false,
        // เพิ่ม security options เพื่ออนุญาต iframe
        webSecurity: false,  // ปิด web security (ใช้เฉพาะสำหรับ development)
        allowRunningInsecureContent: true,
        experimentalFeatures: true
      },
      backgroundColor: '#1a1a1a',
    });

    // Load the native VST host HTML file
    const vstHostPath = path.join(__dirname, 'src', 'vst-host-native.html');
    vstWindow.loadFile(vstHostPath, {
        query: {
            path: pluginPath,
            name: pluginName,
            directory: pluginDir
        }
    });

    // Send plugin information to renderer for potential future use
    vstWindow.webContents.on('did-finish-load', () => {
      vstWindow.webContents.send('vst-plugin-loaded', {
        path: pluginPath,
        name: pluginName,
        directory: pluginDir
      });
    });

  } catch (error) {
    console.error(`Failed to open VST plugin: ${error}`);
    throw new Error(`VST Plugin Loading Failed: ${error.message}`);
  }
});

ipcMain.handle('select-vst-folder', async () => {
  console.log('Opening folder selection dialog...');
  const plugins = await selectVstFolder();
  console.log(`Selected ${plugins.length} VST plugins from custom folder`);
  return plugins;
});

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
